{{- $fullName := include "plex-chart.fullname" . -}}
{{- $labels := include "plex-chart.labels" . -}}
{{- range $type, $pvc := .Values.volumes }}
{{- if $pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $type }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  storageClassName: {{ $pvc.className | quote }}
  accessModes:
  {{- if $pvc.readonly }}
    - ReadOnlyMany
  {{- else }}
    - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
{{- end }}